server:
  port: 8088

spring:
  application:
    name: ITQGroup
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
worker:
  submission:
    batch-size: ${SUBMIT_WORKER_BATCH_SIZE:5}
    enabled: true
    cron-expression: ${SUBMISSION_WORKER_CRON_EXPRESSION:*/30 * * * * *}
  approval:
    batch-size: ${APPROVE_WORKER_BATCH_SIZE:5}
    enabled: true
    cron-expression: ${APPROVAL_WORKER_CRON_EXPRESSION:*/30 * * * * *}
logging:
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/app.%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 7
  pattern:
    console: "%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n"
  level:
    root: info